@startuml

[*] --> ModeSelect
ModeSelect : 1.NORMAL
ModeSelect : 2.CHISATO
ModeSelect : ※稀に2のモードになる

ModeSelect --> NORMAL
ModeSelect --> CHISATO

state NORMAL {
    最初 --> グーを出す
    最初 --> グー以外を出す
    最初 --> 出さない

    グーを出す --> 通常のジャンケン勝負
    通常のジャンケン勝負 : あいこの場合は「あいこで」勝負

    グー以外を出す : 突っ込みが入ってやり直し
    グー以外を出す --> 突っ込み後

    突っ込み後 : CPUがパーを出してくる
    突っ込み後 --> O_プレイヤーがグー
    O_プレイヤーがグー: 「バカめー」で終了
    
    突っ込み後 -->O_プレイヤーがパー
    O_プレイヤーがパー : 「やめやめ」で終了

    突っ込み後 --> O_プレイヤーがチョキ
    O_プレイヤーがチョキ : 「卑怯者」と罵られる

    出さない : ちゃんとやれと言われてやり直し

    出さない --> ちゃんとやる
    ちゃんとやる : CPUがグーを出してくる

    ちゃんとやる --> プレイヤーがグー
    プレイヤーがグー --> 通常のジャンケン勝負

    ちゃんとやる --> プレイヤーがチョキ
    プレイヤーがチョキ : プレイヤーの負け

    ちゃんとやる --> プレイヤーがパー
    プレイヤーがパー : プレイヤーの勝ち
}

state CHISATO {
    最初はグー --> C_グーを出す
    最初はグー --> C_グー以外を出す

    C_グー以外を出す : 罵られて終了

    C_グーを出す : じゃんけんへ進む

    C_グーを出す --> C_プレイヤーがグー
    C_プレイヤーがグー : CPUの勝ち

    C_グーを出す --> C_プレイヤーがチョキ
    C_プレイヤーがチョキ : C_あいこ勝負

    C_グーを出す --> C_プレイヤーがパー
    C_プレイヤーがパー : プレイヤーの負け

    C_プレイヤーがチョキ --> C_あいこ勝負
    C_あいこ勝負 --> C_あいこの次も同じ手
    C_あいこの次も同じ手 : プレイヤーの負け

    C_あいこ勝負 --> C_あいこに負ける手
    C_あいこに負ける手 : 必ずあいこになる

    C_あいこに負ける手 --> C_あいこ勝負

    C_あいこ勝負 --> C_あいこに勝つ手
    C_あいこに勝つ手 : プレイヤーの負け

}

@enduml