@startuml

package PicoLib{
    class Buzzer{
        __init__(pin_no: int)
        --
        beep(ms: int = 100)
    }

    class InputSwitch{
        __init__(pin_no: int)
        --
        is_on() -> bool
        is_off() -> bool
    }

    class Led{
        __init__(pin_no: int)
        --
        on()
        off()
    }

    class ScoreBord{
        __init__(
        i2c_ch: int,
        scl_pin_no: int,
        sda_pin_no: int,
        is_debug: bool = False)
        --
        set_eng_pin(pin_no: int) 
        set_i2c_addr(addr: int, is_debug: bool = False)
        display_off()
        output_score(score: int, is_debug: bool = False)
        score_update_thread_start()
        scre_update_thread_stop()
        output_message(message: str)
        output_foul()
        display_check()
    }

    class ReflexesGame{
        __init__(
        lightes: list[Led],
        buttons: list[InputSwitch],
        buzzer_l: Buzzer,
        buzzer_h: Buzzer,
        score_bord: ScoreBord,
        led_highscore: Led,
        led_timeup: Led,
        order_size: int = 10)
        --
        parts_check()
        game_stert()
    }
}


@enduml